services:
  mongodb-test:
    container_name: mongodb-test
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dam-user
      - MONGO_INITDB_ROOT_PASSWORD=dam-pass
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
