version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  slack: circleci/slack@4.12.6
  jq: circleci/jq@2.2.0

aliases:
  - &install-deps
    run:
      name: Install dependencies
      command: npm ci
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &save-cache
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
  - &persist-dist
    persist_to_workspace:
      root: .
      paths:
        - 'dist'
  - &build-package
    run:
      name: Build
      command: npm run build
  - &update-npm-version
    run:
      name: Update NPM version
      command: 'sudo npm install -g npm@latest'
  - &notify-fail
    slack/notify:
      event: fail
      template: basic_fail_1
  - &notify-success
    slack/notify:
      event: pass
      template: basic_success_1

commands:
  unit-tests-parallelized-command:
    description: "Split and run unit tests with JUnit as reporter"
    steps:
      - run:
          name: Create report folder
          command: mkdir -p reports/junit
      - run:
          name: Split and run unit tests
          command: |
            UT_FILES=$(circleci tests glob "libs/**/*.spec.ts" | circleci tests split --split-by=timings)
            echo $UT_FILES
            npm run test:ci:junit $UT_FILES
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/junit
      - store_test_results:
          path: reports/junit

  unit-tests-not-parallelized-command:
    description: "Run unit tests with Sonar as reporter"
    steps:
      - run:
          name: Create report folder
          command: mkdir -p reports/sonar
      - run:
          name: Run unit tests
          command: npm run test:ci:sonar
      - store_artifacts:
          path: reports/sonar
          destination: reports/sonar

  release-command:
    description: "Create release PR on Github"
    steps:
      - run:
          name: Create release PR on Github
          command: npx release-please release-pr
            --token ${GH_TOKEN}
            --repo-url ${GH_OWNER}/${GH_REPO}

  pre-release-command:
    description: "Create prerelease PR on Github"
    steps:
      - run:
          name: Create prerelease PR on Github
          command: npx release-please release-pr
            --token ${GH_TOKEN}
            --repo-url ${GH_OWNER}/${GH_REPO}
            --versioning-strategy prerelease

jobs:
  dependencies-job:
    description: "Install dependencies, update cache"
    docker:
      - image: cimg/node:20.5.0
    resource_class: medium
    steps:
      - checkout
      - *update-npm-version
      - *restore-cache
      - *install-deps
      - *save-cache

  build-job:
    docker:
      - image: cimg/node:20.5.0
    resource_class: medium
    parameters:
      persist:
        type: boolean
        default: false
    steps:
      - checkout
      - *restore-cache
      - *build-package
      - when:
          condition: << parameters.persist >>
          steps:
            - *persist-dist
      - *notify-fail
      - *notify-success

  test-job:
    docker:
      - image: cimg/node:20.5.0
    resource_class: medium
    parallelism: 8
    steps:
      - checkout
      - *restore-cache
      - unit-tests-parallelized-command
      - *notify-fail
      - *notify-success

  sonarcloud-job:
    docker:
      - image: cimg/node:20.5.0
    resource_class: medium
    steps:
      - checkout
      - *restore-cache
      - unit-tests-not-parallelized-command
      - sonarcloud/scan
      - *notify-fail
      - *notify-success

  pre-release-job:
    docker:
      - image: cimg/node:20.5.0
    resource_class: medium
    steps:
      - checkout
      - pre-release-command

workflows:
  ci-build-and-test-workflow:
    when:
      not: << pipeline.git.tag >>
    jobs:
      - dependencies-job
      - build-job:
          requires:
            - dependencies-job
          context: SLACK
          filters:
            branches:
              ignore:
                - test
      - test-job:
          requires:
            - dependencies-job
          context:
            - SONARCLOUD
            - SLACK
          filters:
            branches:
              ignore:
                - test

  cd-pre-release-workflow:
    when:
      equal: [ << pipeline.git.tag >>, prerelease ]
    jobs:
      - pre-release-job:
          context:
            - GIT
          filters:
            branches:
              ignore: /.*/
            tags:
              only: prerelease
