import { ModuleMetadata, NestInterceptor, Type, ValidationPipeOptions } from '@nestjs/common';
import type { Request } from 'express';
import {
  AuthAbilityPredicate,
  BeforeRegisterContext,
  BroadcastAbilityPredicate,
  BroadcastRooms,
  DynamicApiResetPasswordCallback,
  BeforeSaveCallback,
  AfterSaveCallback,
  DynamicApiWebSocketOptions,
} from '../../../interfaces';
import { BaseEntity } from '../../../models';

type DynamicApiJWTOptions = {
  secret: string;
  expiresIn?: string | number;
  refreshTokenExpiresIn?: string | number;
  refreshSecret?: string;
};

type DynamicApiAuthBroadcastConfig<Entity extends BaseEntity = any> = {
  enabled: boolean | BroadcastAbilityPredicate<Partial<Entity>>;
  eventName?: string;
  fields?: (keyof Entity)[];
  rooms?: BroadcastRooms<Partial<Entity>>;
};

type DynamicApiLoginOptions<Entity extends BaseEntity = any> = {
  loginField?: keyof Entity;
  passwordField?: keyof Entity;
  callback?: AfterSaveCallback<Entity>;
  abilityPredicate?: AuthAbilityPredicate;
  additionalFields?: (keyof Entity)[];
  useInterceptors?: Type<NestInterceptor>[];
  broadcast?: DynamicApiAuthBroadcastConfig<Entity>;
  /**
   * Optional async function called before the Passport local strategy validates credentials.
   * Receives the full HTTP request. If it returns a non-null user, that user is used directly
   * and `validateUser(login, pass)` is skipped. Ideal for passwordless or device-token flows.
   */
  customValidate?: (req: Request) => Promise<Entity | null>;
  /**
   * Optional custom Passport strategy class to replace the default local strategy generated by MDA.
   * If provided, this class is registered as-is under the `local` Passport strategy name.
   */
  useStrategy?: Type<any>;
}

type DynamicApiGetAccountOptions<Entity extends BaseEntity = any> = {
  callback?: AfterSaveCallback<Entity>;
  useInterceptors?: Type<NestInterceptor>[];
  broadcast?: DynamicApiAuthBroadcastConfig<Entity>;
};

/**
 * Options for the `register` auth route.
 *
 * @typeParam Entity - The user entity class.
 * @typeParam TExtra - Optional shape of extra request fields (e.g. `deviceToken`) that are
 *   declared in `additionalFields` but not part of the entity type.
 *   Defaults to `Record<never, never>` (no extras) so existing usage compiles unchanged.
 *
 * @example — typed extra fields, zero casts in callback
 * ```typescript
 * import { DynamicApiRegisterOptions, BeforeRegisterContext } from 'mongodb-dynamic-api';
 *
 * const registerOptions: DynamicApiRegisterOptions<User, { deviceToken?: string }> = {
 *   additionalFields: [{ name: 'deviceToken', required: false }],
 *   beforeSaveCallback: async (user, ctx, methods) => {
 *     const token = user?.deviceToken; // ✅ fully typed, no cast
 *     return { ...user, role: 'member' };
 *   },
 * };
 * ```
 */
type DynamicApiRegisterOptions<Entity extends BaseEntity = any, TExtra = Record<never, never>> = {
  beforeSaveCallback?: BeforeSaveCallback<Entity & TExtra, BeforeRegisterContext>;
  callback?: AfterSaveCallback<Entity>;
  protected?: boolean;
  abilityPredicate?: AuthAbilityPredicate;
  additionalFields?: (keyof (Entity & TExtra) | { name: keyof (Entity & TExtra); required?: boolean })[];
  useInterceptors?: Type<NestInterceptor>[];
  broadcast?: DynamicApiAuthBroadcastConfig<Entity>;
};

type DynamicApiUpdateAccountOptions<Entity extends BaseEntity = any> = {
  beforeSaveCallback?: BeforeSaveCallback<Entity>;
  callback?: AfterSaveCallback<Entity>;
  abilityPredicate?: AuthAbilityPredicate;
  additionalFieldsToExclude?: (keyof Entity)[];
  useInterceptors?: Type<NestInterceptor>[];
  broadcast?: DynamicApiAuthBroadcastConfig<Entity>;
  /**
   * When true, the updateAccount endpoint returns a fresh `{ accessToken, refreshToken }`
   * instead of the updated entity, so the client can seamlessly refresh its JWT after
   * a profile change without a separate /refresh-token call.
   */
  refreshTokenOnUpdate?: boolean;
};

type DynamicApiResetPasswordOptions<Entity extends BaseEntity = any> = {
  emailField?: keyof Entity | string;
  expirationInMinutes?: number;
  beforeChangePasswordCallback?: BeforeSaveCallback<Entity>;
  resetPasswordCallback?: DynamicApiResetPasswordCallback<Entity>;
  resetPasswordUseInterceptors?: Type<NestInterceptor>[];
  changePasswordCallback?: AfterSaveCallback<Entity>;
  changePasswordAbilityPredicate?: AuthAbilityPredicate;
  changePasswordUseInterceptors?: Type<NestInterceptor>[];
};

type DynamicApiRefreshTokenOptions<Entity extends BaseEntity = any> = {
  useInterceptors?: Type<NestInterceptor>[];
  /**
   * Field in the entity where the hashed refresh token is stored.
   * Required for server-side token rotation and revocation.
   * If not configured, logout will not invalidate existing refresh tokens server-side
   * (a warning will be logged at runtime).
   */
  refreshTokenField?: keyof Entity;
  /**
   * When true, the refresh token is sent/read as an httpOnly cookie exclusively (Bearer header disabled).
   * When false (default), the refresh token is sent/read via the Authorization Bearer header exclusively.
   */
  useCookie?: boolean;
};

type PasswordlessOptions<Entity extends BaseEntity = any> = {
  /**
   * How long the OTP code stays valid, in minutes.
   * Defaults to 10.
   */
  otpExpirationMinutes?: number;
  /**
   * Optional custom code generator.
   * Defaults to a random 6-digit numeric string: "123456".
   */
  generateCode?: () => string;
  /**
   * Required callback that delivers the one-time code to the user
   * (e.g. sends an email or SMS).
   * Receives the identifier value (resolved via `loginField`) and the plain code.
   */
  sendCodeCallback: (identifier: string, code: string) => Promise<void>;
  /**
   * Optional callback invoked after successful OTP verification,
   * just before the JWT tokens are returned.
   * Receives the authenticated entity.
   */
  callback?: AfterSaveCallback<Entity>;
};

type DynamicApiAuthOptions<Entity extends BaseEntity = any, RegisterExtra = Record<never, never>> = {
  userEntity: Type<Entity>;
  jwt?: DynamicApiJWTOptions;
  login?: DynamicApiLoginOptions<Entity>;
  getAccount?: DynamicApiGetAccountOptions<Entity>;
  register?: DynamicApiRegisterOptions<Entity, RegisterExtra>;
  updateAccount?: DynamicApiUpdateAccountOptions<Entity>;
  resetPassword?: Partial<DynamicApiResetPasswordOptions<Entity>>;
  refreshToken?: DynamicApiRefreshTokenOptions<Entity>;
  passwordless?: PasswordlessOptions<Entity>;
  validationPipeOptions?: ValidationPipeOptions;
  webSocket?: DynamicApiWebSocketOptions;
  extraImports?: ModuleMetadata['imports'];
  extraProviders?: ModuleMetadata['providers'];
  extraControllers?: ModuleMetadata['controllers'];
};

export type {
  DynamicApiAuthBroadcastConfig,
  DynamicApiAuthOptions,
  DynamicApiRegisterOptions,
  DynamicApiUpdateAccountOptions,
  DynamicApiGetAccountOptions,
  DynamicApiJWTOptions,
  DynamicApiLoginOptions,
  DynamicApiRefreshTokenOptions,
  DynamicApiResetPasswordOptions,
  PasswordlessOptions,
};
