import { ExecutionContext, Injectable } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { AuthGuard } from '@nestjs/passport';
import { IS_PUBLIC_KEY } from '../decorators';
import { DynamicApiGlobalState } from '../interfaces';
import { MongoDBDynamicApiLogger } from '../logger';

@Injectable()
export class DynamicApiJwtAuthGuard extends AuthGuard('jwt') {
  private readonly logger = new MongoDBDynamicApiLogger(DynamicApiJwtAuthGuard.name);

  constructor(
    private readonly reflector: Reflector,
    private readonly state: DynamicApiGlobalState,
  ) {
    super();
  }

  canActivate(context: ExecutionContext) {
    const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);

    if (isPublic || !this.state.isAuthEnabled) {
      return true;
    }

    return super.canActivate(context);
  }

  /**
   * Overrides Passport's default `handleRequest` to log the *real* rejection reason
   * (missing token, invalid signature, expired token, …) server-side before falling back
   * to the default behaviour (throws a generic `UnauthorizedException`, unchanged for callers).
   * The reason is never exposed to the client — only visible when
   * `MONGODB_DYNAMIC_API_LOGGER` is set to `WARN` or more verbose.
   * Note: this guard is registered globally (`APP_GUARD`) and therefore covers every Nest
   * controller in the application, not just the routes generated by DynamicAPI.
   */
  handleRequest<TUser = unknown>(
    err: unknown,
    user: TUser,
    info: unknown,
    context: ExecutionContext,
    status?: unknown,
  ): TUser {
    if (!user) {
      this.logger.warn(`Request rejected: ${this.resolveRejectionReason(err, info)}`);
    }

    return super.handleRequest(err, user, info, context, status);
  }

  private resolveRejectionReason(err: unknown, info: unknown): string {
    if (err instanceof Error) {
      return err.message;
    }

    if (info instanceof Error) {
      return info.message || info.name;
    }

    if (typeof info === 'string' && info) {
      return info;
    }

    return 'missing or invalid token';
  }
}
