import { ExecutionContext, Injectable } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { AuthGuard } from '@nestjs/passport';
import { IS_PUBLIC_KEY } from '../decorators';
import { DynamicApiGlobalState } from '../interfaces';
import { MongoDBDynamicApiLogger } from '../logger';

@Injectable()
export class DynamicApiJwtAuthGuard extends AuthGuard('jwt') {
  private readonly logger = new MongoDBDynamicApiLogger(DynamicApiJwtAuthGuard.name);

  constructor(
    private readonly reflector: Reflector,
    private readonly state: DynamicApiGlobalState,
  ) {
    super();
  }

  canActivate(context: ExecutionContext) {
    // `@nestjs/core` v12 changed global `APP_GUARD`s to also run for WebSocket gateway handlers —
    // verified by diffing v11/v12: under v11 this guard was simply never invoked for `ws` contexts,
    // so gateway auth has always been handled entirely by the dedicated socket guards
    // (JwtSocketAuthGuard, AuthSocketPoliciesGuardMixin, ResetPasswordGuard, PasswordlessGuard, ...)
    // applied explicitly per-handler in the gateway mixins — never by this HTTP-oriented guard. Under
    // v12, letting it run for `ws` breaks every gateway handler that isn't already behind one of those
    // guards (e.g. the public auth-register/auth-login events): passport's `AuthGuard()` mixin calls
    // `context.switchToHttp().getRequest()`, which for a `ws` context returns the raw connected socket
    // (not an HTTP request), and passport-jwt's extractor then throws reading `.headers` off it. This
    // guard's own doc comment already scoped it to "every Nest controller" (HTTP) — this bypass just
    // makes that pre-existing design intent explicit instead of relying on the framework's old,
    // now-changed behaviour to enforce it.
    if (context.getType() !== 'http') {
      return true;
    }

    const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);

    if (isPublic || !this.state.isAuthEnabled) {
      return true;
    }

    return super.canActivate(context);
  }

  /**
   * Overrides Passport's default `handleRequest` to log the *real* rejection reason
   * (missing token, invalid signature, expired token, …) server-side before falling back
   * to the default behaviour (throws a generic `UnauthorizedException`, unchanged for callers).
   * The reason is never exposed to the client — only visible when
   * `MONGODB_DYNAMIC_API_LOGGER` is set to `WARN` or more verbose.
   * Note: this guard is registered globally (`APP_GUARD`) and therefore covers every Nest
   * controller in the application, not just the routes generated by DynamicAPI.
   */
  handleRequest<TUser = unknown>(
    err: unknown,
    user: TUser,
    info: unknown,
    context: ExecutionContext,
    status?: unknown,
  ): TUser {
    if (!user) {
      this.logger.warn(`Request rejected: ${this.resolveRejectionReason(err, info)}`);
    }

    return super.handleRequest(err, user, info, context, status);
  }

  private resolveRejectionReason(err: unknown, info: unknown): string {
    if (err instanceof Error) {
      return err.message;
    }

    if (info instanceof Error) {
      return info.message || info.name;
    }

    if (typeof info === 'string' && info) {
      return info;
    }

    return 'missing or invalid token';
  }
}
